### PR TITLE
Added clone method to the cart object

### PR DESCRIPTION
**Pull request by melmothx**

### CODE REVIEW

**Comment by SysPete** [comment]
@melmothx since this is pure schema code I'd really prefer to see this as a method in `Interchange6::Schema`. Don't want to add stuff here that we'd have to replicate to the D2 plugin. I'd also like to see it all in a single transaction and also using `DBIx::Class::Row->copy` where possible since server-side copy is much cheaper (cascade copy is on for that relation).

@racke comments?

**Comment by racke** [comment]
Yes, that makes a lot of sense @SysPete.

**Comment by racke** [comment]
Moved to Interchange6::Schema.

**Comment by melmothx** [comment]
I guess you should keep the tests, though.

**Pull request closed without merging**
